metadata.format.version = "1.1"

[versions]

adventure = "4.17.0"
opennbt = "c62816538c"
mcauthlib = "627c9f603d"
math = "2.0"
fastutil = "b3ff25af48"
netty = "4.1.108.Final"
netty-io_uring = "0.0.24.Final"
checkerframework = "3.42.0"
junit = "5.8.2"

# buildSrc
indra = "3.1.3"
lombok-version = "1.18.30"
lombok-plugin = "8.4"

[libraries]

adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }
adventure-text-serializer-json-legacy-impl = { module = "net.kyori:adventure-text-serializer-json-legacy-impl", version.ref = "adventure" }
adventure-text-serializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-text-serializer-ansi = { module = "net.kyori:adventure-text-serializer-ansi", version.ref = "adventure" }

opennbt = { module = "com.github.rfresh2:OpenNBT", version.ref = "opennbt" }
mcauthlib = { module = "com.github.rfresh2:MCAuthLib", version.ref = "mcauthlib" }

math-api = { module = "org.cloudburstmc.math:api", version.ref = "math" }
math-immutable = { module = "org.cloudburstmc.math:immutable", version.ref = "math" }

fastutil-object2int-maps = { module = "com.github.rfresh2.fastutil:object-int-maps", version.ref = "fastutil" }
fastutil-int2object-maps = { module = "com.github.rfresh2.fastutil:int-object-maps", version.ref = "fastutil" }
fastutil-int2int-maps = { module = "com.github.rfresh2.fastutil:int-int-maps", version.ref = "fastutil" }

netty-all = { module = "io.netty:netty-all", version.ref = "netty" }
netty-incubator-transport-native-io_uring = { module = "io.netty.incubator:netty-incubator-transport-native-io_uring", version.ref = "netty-io_uring" }

velocity-natives = { module = "com.velocitypowered:velocity-native", version = "3.3.0-SNAPSHOT" }

checkerframework-qual = { module = "org.checkerframework:checker-qual", version.ref = "checkerframework" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

# buildSrc
indra-common = { module = "net.kyori:indra-common", version.ref = "indra" }
indra-git = { module = "net.kyori:indra-git", version.ref = "indra" }
lombok = { module = "io.freefair.gradle:lombok-plugin", version.ref = "lombok-plugin" }

[bundles]

adventure = ["adventure-text-serializer-gson", "adventure-text-serializer-json-legacy-impl", "adventure-text-serializer-legacy", "adventure-text-serializer-ansi"]
math = ["math-api", "math-immutable"]
fastutil = ["fastutil-object2int-maps", "fastutil-int2object-maps", "fastutil-int2int-maps"]
netty = ["netty-all", "netty-incubator-transport-native-io_uring"]
